@startuml SistemaLeilao

class Category {
 -name: Char
 -description: Text
 -status: Boolean
 +toString()
}

class Item {
 -name: Char
 -description: Text
 -state: CharChoices
 -price: Float
 -photo: Image
 -category: ForeignKey[Category]
 +toString()
}

class User {
 -id: Char
 -balance: Float
 -reputation: Float
 -gender: CharChoices
 +toString()
}

class Auctioneer {
 -company: Char
 -evaluation: Float
 -commission: Float
 -status: Boolean
 +toString()
}

class ContactChannel {
 -name: Char
 -content_type: Text
 -preferential_contact: Char
 +toString()
}

class Person {
 -name: Char
 -email: Email
 -password: Char
 -phone: Char
 -date_sign: DateTime
 +toString()
}

class Auction {
 -title: Char
 -description: Text
 -date_begin: DateTime
 -date_end: DateTime
 -status: CharChoices
 -initial_value: Float
 -item: ForeignKey[Item]
 -auctioneer: ForeignKey[Auctioneer]
 +toString()
}

class AuctionItem {
 -quant: Int
 -value: Float
 -sub_total: Float
 -item: ForeignKey[Item]
 -auction: ForeignKey[Auction]
 +toString()
}

class AuctionBid {
 -value: Decimal
 -status: CharChoices
 -user: ForeignKey[User]
 -auctionitem: ForeignKey[AuctionItem]
 +toString()
 +end_bid()
}

class Payment {
 -total: Float
 -payment_mode: CharChoices
 -status: CharChoices
 -data_payment: DateTime
 -user: ForeignKey[User]
 +toString()
}

class ReceiptPayment {
 -number: Char
 -issue_date: Date
 -payment: OneToOne[Payment]
 +toString()
}

class Notification {
 -title: Char
 -mesage: Text
 -type: CharChoices
 -date_sent: DateTime
 -user: ForeignKey[User]
 +toString()
}

Category *--> "1..n" Item
Item *--> "1..n" AuctionItem
Auction *--> "1..n" AuctionItem
Auction *--> "1..n" AuctionBid
User *--> "1..n" AuctionBid
User *--> "n..n" Auction
AuctionBid *--> "1..n" Payment
Payment *--> "1..1" ReceiptPayment
Auctioneer *--> "1..n" Auction
ContactChannel *--> "1..n" User
User *--> "0..n" Notification
User -up-|> Person
Auctioneer -up-|> Person

@enduml
